// lib/mock-data.ts
// Static seed data — mirrors prisma/seed.ts exactly.
// Used by all API routes so CribConnect works on Vercel without an external database.

export const MOCK_USERS = [
  {
    id: "student-chidi",
    email: "chidi@student.unilag.edu.ng",
    name: "Chidi Nwosu",
    role: "STUDENT",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=chidi",
    phone: "+234 801 234 5678",
    whatsapp: "2348012345678",
    city: "Enugu",
    currentSchool: "University of Lagos (UNILAG)",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "agent-kolawole",
    email: "kolawole@cribconnect.ng",
    name: "Kolawole Adeyemi",
    role: "AGENT",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kolawole",
    phone: "+234 802 345 6789",
    whatsapp: "2348023456789",
    city: "Lagos",
    currentSchool: null,
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "agent-bisi",
    email: "bisi@cribconnect.ng",
    name: "Bisi Okafor",
    role: "AGENT",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bisi",
    phone: "+234 803 456 7890",
    whatsapp: "2348034567890",
    city: "Lagos",
    currentSchool: null,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "admin-tola",
    email: "tola@cribconnect.ng",
    name: "Tola Balogun",
    role: "ADMIN",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tola",
    phone: "+234 804 567 8901",
    whatsapp: "2348045678901",
    city: "Lagos",
    currentSchool: null,
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const MOCK_AGENT_PROFILES = [
  {
    id: "profile-kolawole",
    userId: "agent-kolawole",
    agencyName: "Adeyemi Properties & Housing",
    ninNumber: "NIN-KOL-001",
    idDocumentUrl: "https://images.unsplash.com/photo-1568992688065-536aad8a12f6?w=400",
    verificationStatus: "VERIFIED",
    verificationNotes: "NIN verified, Lagos broker license confirmed",
    tier: "PRO",
    badges: JSON.stringify(["Verified Agent", "Top Rated", "UNILAG Specialist", "Pro Member"]),
    rating: 4.9,
    reviewCount: 47,
    bio: "10+ years finding student accommodation near UNILAG and YabaTech. I specialise in transparent, scam-free lettings with full fee breakdowns. Every listing I manage has been personally inspected.",
    yearsExperience: 10,
    campusSpecialization: "University of Lagos (UNILAG)",
    coverageAreas: JSON.stringify(["Akoka", "Yaba", "Onike", "Abule-Oja"]),
    featuredListingCredits: 5,
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "profile-bisi",
    userId: "agent-bisi",
    agencyName: "Bisi Homes",
    ninNumber: "NIN-BSI-002",
    idDocumentUrl: null,
    verificationStatus: "PENDING",
    verificationNotes: null,
    tier: "FREE",
    badges: JSON.stringify([]),
    rating: 4.3,
    reviewCount: 8,
    bio: "New to the platform but experienced in Bariga and Onike rentals. Working on getting fully verified soon.",
    yearsExperience: 3,
    campusSpecialization: "Yaba College of Technology (YabaTech)",
    coverageAreas: JSON.stringify(["Bariga", "Onike", "Yaba"]),
    featuredListingCredits: 0,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const MOCK_LISTINGS = [
  {
    id: "listing-1",
    agentId: "agent-kolawole",
    title: "Modern Self-Contain | 4 Mins to UNILAG New Hall Gate",
    description: "Freshly tiled self-contain apartment with constant water supply via borehole and a dedicated generator line. The compound has 24-hour security and a CCTV system. Ideal for a first-year or postgrad student who wants peace and privacy close to campus.",
    price: 450000,
    currency: "NGN",
    period: "per year",
    propertyType: "SELF_CONTAIN",
    bedrooms: 1,
    bathrooms: 1,
    address: "14B Jaja Street, Akoka",
    neighborhood: "Akoka",
    city: "Lagos",
    universityNearby: "University of Lagos (UNILAG)",
    distanceToCampusMinutes: 4,
    distanceDescription: "4 mins walk to UNILAG New Hall Gate",
    latitude: 6.5186,
    longitude: 3.3881,
    photos: JSON.stringify([
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
    ]),
    videoTourUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    amenities: JSON.stringify(["Borehole Water", "Generator Backup", "24/7 Security", "CCTV", "Tiled Floors"]),
    isFeatured: true,
    viewsCount: 342,
    inquiriesCount: 28,
    isAvailable: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "listing-2",
    agentId: "agent-kolawole",
    title: "Spacious 1-Bedroom Flat | Onike, 8 Mins to UNILAG Main Gate",
    description: "Well-maintained 1-bedroom apartment in a quiet estate. Includes a small study corner perfect for reading, a full kitchen with gas cooker point, and parking space. The compound is fenced with security guard coverage.",
    price: 600000,
    currency: "NGN",
    period: "per year",
    propertyType: "ONE_BED",
    bedrooms: 1,
    bathrooms: 1,
    address: "7 Araromi Street, Onike",
    neighborhood: "Onike",
    city: "Lagos",
    universityNearby: "University of Lagos (UNILAG)",
    distanceToCampusMinutes: 8,
    distanceDescription: "8 mins walk to UNILAG Main Gate",
    latitude: 6.5142,
    longitude: 3.3792,
    photos: JSON.stringify([
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800",
    ]),
    videoTourUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    amenities: JSON.stringify(["Fenced Compound", "Security Guard", "Parking Space", "Gas Cooker Point", "Borehole Water"]),
    isFeatured: true,
    viewsCount: 218,
    inquiriesCount: 15,
    isAvailable: true,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "listing-3",
    agentId: "agent-kolawole",
    title: "Budget Self-Contain | Abule-Oja, 6 Mins to UNILAG 2nd Gate",
    description: "Clean and affordable self-contain for students on a tight budget. Recently repainted with new ceiling fans. Shared borehole water, generator access available at extra cost of ₦5,000/month.",
    price: 350000,
    currency: "NGN",
    period: "per year",
    propertyType: "SELF_CONTAIN",
    bedrooms: 1,
    bathrooms: 1,
    address: "22 Fadeyi Road, Abule-Oja",
    neighborhood: "Abule-Oja",
    city: "Lagos",
    universityNearby: "University of Lagos (UNILAG)",
    distanceToCampusMinutes: 6,
    distanceDescription: "6 mins walk to UNILAG 2nd Gate",
    latitude: 6.5098,
    longitude: 3.3745,
    photos: JSON.stringify([
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
      "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800",
    ]),
    videoTourUrl: null,
    amenities: JSON.stringify(["Shared Borehole", "Recently Renovated", "Ceiling Fans"]),
    isFeatured: false,
    viewsCount: 156,
    inquiriesCount: 22,
    isAvailable: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "listing-4",
    agentId: "agent-bisi",
    title: "2-Bedroom Shared Flat | Bariga, Near St. Finbarr's Road",
    description: "Ideal for two students sharing. Each room has a separate key, shared bathroom and kitchen. Located minutes from YabaTech and bus stops to UNILAG. Landlord on-site and responsive.",
    price: 480000,
    currency: "NGN",
    period: "per year",
    propertyType: "TWO_BED",
    bedrooms: 2,
    bathrooms: 1,
    address: "5 Shipeolu Street, Bariga",
    neighborhood: "Bariga",
    city: "Lagos",
    universityNearby: "Yaba College of Technology (YabaTech)",
    distanceToCampusMinutes: 12,
    distanceDescription: "12 mins to YabaTech, 20 mins bus to UNILAG",
    latitude: 6.5321,
    longitude: 3.3865,
    photos: JSON.stringify([
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800",
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800",
    ]),
    videoTourUrl: null,
    amenities: JSON.stringify(["Shared Kitchen", "Landlord On-Site", "Water Supply", "Close to Bus Stop"]),
    isFeatured: false,
    viewsCount: 89,
    inquiriesCount: 11,
    isAvailable: true,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "listing-5",
    agentId: "agent-kolawole",
    title: "Premium Studio Apartment | Yaba, Fully Furnished & AC",
    description: "Top-tier serviced studio for professionals or senior students. Includes 24/7 inverter power, high-speed fiber WiFi, and fully furnished interior (bed, wardrobe, sofa, TV stand). Modern building with intercom system.",
    price: 850000,
    currency: "NGN",
    period: "per year",
    propertyType: "STUDIO",
    bedrooms: 1,
    bathrooms: 1,
    address: "18 Herbert Macaulay Way, Yaba",
    neighborhood: "Yaba",
    city: "Lagos",
    universityNearby: "Yaba College of Technology (YabaTech)",
    distanceToCampusMinutes: 10,
    distanceDescription: "10 mins walk to YabaTech, 15 mins bus to UNILAG",
    latitude: 6.5058,
    longitude: 3.3703,
    photos: JSON.stringify([
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800",
    ]),
    videoTourUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    amenities: JSON.stringify(["24/7 Inverter Power", "Fiber WiFi", "Fully Furnished", "Air Conditioning", "Intercom System", "TV Stand"]),
    isFeatured: true,
    viewsCount: 501,
    inquiriesCount: 43,
    isAvailable: true,
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "listing-6",
    agentId: "agent-bisi",
    title: "Self-Contain | Onike Road, 5 Mins to UNILAG Pedestrian Gate",
    description: "Cosy self-contain with private bathroom and kitchenette. The compound has a small garden area and is very quiet. Perfect for students who value a calm study environment. Water is via overhead tank topped daily.",
    price: 400000,
    currency: "NGN",
    period: "per year",
    propertyType: "SELF_CONTAIN",
    bedrooms: 1,
    bathrooms: 1,
    address: "3 Olateju Street, Onike",
    neighborhood: "Onike",
    city: "Lagos",
    universityNearby: "University of Lagos (UNILAG)",
    distanceToCampusMinutes: 5,
    distanceDescription: "5 mins walk to UNILAG Pedestrian Gate",
    latitude: 6.5165,
    longitude: 3.3812,
    photos: JSON.stringify([
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800",
      "https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800",
    ]),
    videoTourUrl: null,
    amenities: JSON.stringify(["Overhead Tank Water", "Private Kitchenette", "Garden Area", "Quiet Compound"]),
    isFeatured: false,
    viewsCount: 134,
    inquiriesCount: 18,
    isAvailable: true,
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const MOCK_HOUSING_REQUESTS = [
  {
    id: "request-1",
    studentId: "student-chidi",
    title: "Self-contain near UNILAG New Hall Gate, max ₦500k, moving Sept 1",
    description: "Incoming 100-level student from Enugu. Need a clean, safe self-contain within 10 minutes walk of UNILAG New Hall Gate. Must have constant water supply and generator backup. Budget is strictly ₦500,000/year all-in (rent + agency). I am a quiet student, no parties.",
    targetUniversity: "University of Lagos (UNILAG)",
    preferredAreas: JSON.stringify(["Akoka", "Onike"]),
    maxBudget: 500000,
    currency: "NGN",
    propertyType: "SELF_CONTAIN",
    moveInDate: "2024-09-01",
    duration: "1 Year",
    needsRoommate: false,
    status: "OPEN",
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "request-2",
    studentId: "student-chidi",
    title: "2-bed shared flat wanted | Yaba/Bariga, moving Feb, budget ₦600k total",
    description: "Postgrad student looking for a 2-bedroom flat to share with one other student (friend from school). Yaba or Bariga preferred. Need decent water supply, don't require generator but it's a plus. Target budget ₦300k each (₦600k total per year). Quiet, no drama.",
    targetUniversity: "University of Lagos (UNILAG)",
    preferredAreas: JSON.stringify(["Yaba", "Bariga"]),
    maxBudget: 600000,
    currency: "NGN",
    propertyType: "TWO_BED",
    moveInDate: "2024-02-15",
    duration: "1 Year",
    needsRoommate: true,
    status: "OPEN",
    createdAt: new Date("2024-01-13"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const MOCK_PROPOSALS = [
  {
    id: "proposal-1",
    requestId: "request-1",
    agentId: "agent-kolawole",
    listingId: "listing-1",
    pitchMessage: "Hi Chidi! I have the perfect match for you. My listing at 14B Jaja Street is exactly 4 minutes from New Hall Gate, has borehole water and dedicated generator, and I can do ₦450,000 all-in for one year. Agency fee is ₦45,000 (10%) and caution deposit is ₦45,000. Total move-in: ₦540,000. I can arrange a video call walkthrough today.",
    proposedPrice: 450000,
    currency: "NGN",
    period: "per year",
    agencyFee: 45000,
    cautionFee: 45000,
    totalUpfront: 540000,
    status: "SUBMITTED",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "proposal-2",
    requestId: "request-1",
    agentId: "agent-bisi",
    listingId: "listing-6",
    pitchMessage: "Hello! I have a lovely self-contain at 3 Olateju Street, 5 mins to UNILAG pedestrian gate. Asking ₦400k rent. Agency fee ₦40k, caution ₦40k. Very quiet compound, perfect for serious students. I'm pending verification but have been active in this area for 3 years.",
    proposedPrice: 400000,
    currency: "NGN",
    period: "per year",
    agencyFee: 40000,
    cautionFee: 40000,
    totalUpfront: 480000,
    status: "SUBMITTED",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const MOCK_MESSAGES = [
  {
    id: "msg-1",
    senderId: "student-chidi",
    recipientId: "agent-kolawole",
    requestId: "request-1",
    listingId: "listing-1",
    content: "Hi Kolawole, I saw your proposal. Can we schedule a video walkthrough of the Jaja Street apartment?",
    isRead: true,
    createdAt: new Date("2024-01-15T10:00:00"),
  },
  {
    id: "msg-2",
    senderId: "agent-kolawole",
    recipientId: "student-chidi",
    requestId: "request-1",
    listingId: "listing-1",
    content: "Hello Chidi! Absolutely, I can do a live video tour today at 3pm or tomorrow morning. Which works for you? The unit is freshly cleaned and move-in ready.",
    isRead: false,
    createdAt: new Date("2024-01-15T10:15:00"),
  },
];

export const MOCK_REVIEWS = [
  {
    id: "review-1",
    agentProfileId: "profile-kolawole",
    studentId: "student-chidi",
    rating: 5,
    comment: "Kolawole was absolutely professional. He showed me 3 properties, was transparent about all fees upfront, and helped me move in within a week. 100% recommend for any incoming UNILAG student!",
    createdAt: new Date("2024-01-10"),
  },
];

// Helper to get enriched listing with agent info
export function getListingWithAgent(listing: typeof MOCK_LISTINGS[0]) {
  const agent = MOCK_USERS.find(u => u.id === listing.agentId)!;
  const agentProfile = MOCK_AGENT_PROFILES.find(p => p.userId === listing.agentId) || null;
  return { ...listing, agent: { ...agent, agentProfile } };
}

// Helper to get enriched request with student + proposals
export function getRequestWithDetails(request: typeof MOCK_HOUSING_REQUESTS[0]) {
  const student = MOCK_USERS.find(u => u.id === request.studentId)!;
  const proposals = MOCK_PROPOSALS.filter(p => p.requestId === request.id).map(p => {
    const agent = MOCK_USERS.find(u => u.id === p.agentId)!;
    const agentProfile = MOCK_AGENT_PROFILES.find(ap => ap.userId === p.agentId) || null;
    const listing = p.listingId ? MOCK_LISTINGS.find(l => l.id === p.listingId) || null : null;
    return { ...p, agent: { ...agent, agentProfile }, listing };
  });
  return { ...request, student, proposals };
}
